---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - k1-installer.jplab.cloud
  resources:
  - k1installers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - k1-installer.jplab.cloud
  resources:
  - k1installers/finalizers
  verbs:
  - update
- apiGroups:
  - k1-installer.jplab.cloud
  resources:
  - k1installers/status
  verbs:
  - get
  - patch
  - update
